// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: expendedora.proto

package expendedorapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemInventario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Cantidad int32  `protobuf:"varint,2,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
}

func (x *ItemInventario) Reset() {
	*x = ItemInventario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInventario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInventario) ProtoMessage() {}

func (x *ItemInventario) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInventario.ProtoReflect.Descriptor instead.
func (*ItemInventario) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInventario) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ItemInventario) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

type Veto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona string `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	Counter int32  `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *Veto) Reset() {
	*x = Veto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Veto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Veto) ProtoMessage() {}

func (x *Veto) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Veto.ProtoReflect.Descriptor instead.
func (*Veto) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{1}
}

func (x *Veto) GetPersona() string {
	if x != nil {
		return x.Persona
	}
	return ""
}

func (x *Veto) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type IDProceso struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maquina int32 `protobuf:"varint,1,opt,name=maquina,proto3" json:"maquina,omitempty"`
	Proceso int32 `protobuf:"varint,2,opt,name=proceso,proto3" json:"proceso,omitempty"`
}

func (x *IDProceso) Reset() {
	*x = IDProceso{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDProceso) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDProceso) ProtoMessage() {}

func (x *IDProceso) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDProceso.ProtoReflect.Descriptor instead.
func (*IDProceso) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{2}
}

func (x *IDProceso) GetMaquina() int32 {
	if x != nil {
		return x.Maquina
	}
	return 0
}

func (x *IDProceso) GetProceso() int32 {
	if x != nil {
		return x.Proceso
	}
	return 0
}

type SolicitudRegistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *IDProceso `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Direccion string     `protobuf:"bytes,2,opt,name=direccion,proto3" json:"direccion,omitempty"`
}

func (x *SolicitudRegistro) Reset() {
	*x = SolicitudRegistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRegistro) ProtoMessage() {}

func (x *SolicitudRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRegistro.ProtoReflect.Descriptor instead.
func (*SolicitudRegistro) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{3}
}

func (x *SolicitudRegistro) GetId() *IDProceso {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SolicitudRegistro) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type RespuestaRegistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RespuestaRegistro) Reset() {
	*x = RespuestaRegistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaRegistro) ProtoMessage() {}

func (x *RespuestaRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaRegistro.ProtoReflect.Descriptor instead.
func (*RespuestaRegistro) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{4}
}

func (x *RespuestaRegistro) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ActualizacionInventario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origen *IDProceso        `protobuf:"bytes,1,opt,name=origen,proto3" json:"origen,omitempty"`
	Items  []*ItemInventario `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ActualizacionInventario) Reset() {
	*x = ActualizacionInventario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualizacionInventario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizacionInventario) ProtoMessage() {}

func (x *ActualizacionInventario) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizacionInventario.ProtoReflect.Descriptor instead.
func (*ActualizacionInventario) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{5}
}

func (x *ActualizacionInventario) GetOrigen() *IDProceso {
	if x != nil {
		return x.Origen
	}
	return nil
}

func (x *ActualizacionInventario) GetItems() []*ItemInventario {
	if x != nil {
		return x.Items
	}
	return nil
}

type ActualizacionVetos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origen *IDProceso `protobuf:"bytes,1,opt,name=origen,proto3" json:"origen,omitempty"`
	Vetos  []*Veto    `protobuf:"bytes,2,rep,name=vetos,proto3" json:"vetos,omitempty"`
}

func (x *ActualizacionVetos) Reset() {
	*x = ActualizacionVetos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualizacionVetos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizacionVetos) ProtoMessage() {}

func (x *ActualizacionVetos) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizacionVetos.ProtoReflect.Descriptor instead.
func (*ActualizacionVetos) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{6}
}

func (x *ActualizacionVetos) GetOrigen() *IDProceso {
	if x != nil {
		return x.Origen
	}
	return nil
}

func (x *ActualizacionVetos) GetVetos() []*Veto {
	if x != nil {
		return x.Vetos
	}
	return nil
}

type SolicitudEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitante *IDProceso `protobuf:"bytes,1,opt,name=solicitante,proto3" json:"solicitante,omitempty"`
}

func (x *SolicitudEstado) Reset() {
	*x = SolicitudEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEstado) ProtoMessage() {}

func (x *SolicitudEstado) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEstado.ProtoReflect.Descriptor instead.
func (*SolicitudEstado) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{7}
}

func (x *SolicitudEstado) GetSolicitante() *IDProceso {
	if x != nil {
		return x.Solicitante
	}
	return nil
}

type RespuestaEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origen *IDProceso        `protobuf:"bytes,1,opt,name=origen,proto3" json:"origen,omitempty"`
	Items  []*ItemInventario `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Vetos  []*Veto           `protobuf:"bytes,3,rep,name=vetos,proto3" json:"vetos,omitempty"`
}

func (x *RespuestaEstado) Reset() {
	*x = RespuestaEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEstado) ProtoMessage() {}

func (x *RespuestaEstado) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEstado.ProtoReflect.Descriptor instead.
func (*RespuestaEstado) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{8}
}

func (x *RespuestaEstado) GetOrigen() *IDProceso {
	if x != nil {
		return x.Origen
	}
	return nil
}

func (x *RespuestaEstado) GetItems() []*ItemInventario {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RespuestaEstado) GetVetos() []*Veto {
	if x != nil {
		return x.Vetos
	}
	return nil
}

type PingSinc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origen *IDProceso `protobuf:"bytes,1,opt,name=origen,proto3" json:"origen,omitempty"`
}

func (x *PingSinc) Reset() {
	*x = PingSinc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingSinc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingSinc) ProtoMessage() {}

func (x *PingSinc) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingSinc.ProtoReflect.Descriptor instead.
func (*PingSinc) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{9}
}

func (x *PingSinc) GetOrigen() *IDProceso {
	if x != nil {
		return x.Origen
	}
	return nil
}

type PongSinc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *PongSinc) Reset() {
	*x = PongSinc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expendedora_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongSinc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongSinc) ProtoMessage() {}

func (x *PongSinc) ProtoReflect() protoreflect.Message {
	mi := &file_expendedora_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongSinc.ProtoReflect.Descriptor instead.
func (*PongSinc) Descriptor() ([]byte, []int) {
	return file_expendedora_proto_rawDescGZIP(), []int{10}
}

func (x *PongSinc) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_expendedora_proto protoreflect.FileDescriptor

var file_expendedora_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61,
	0x22, 0x44, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x61, 0x72,
	0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61,
	0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x22, 0x3a, 0x0a, 0x04, 0x56, 0x65, 0x74, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x22, 0x3f, 0x0a, 0x09, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x61, 0x71, 0x75, 0x69, 0x6e, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x6d, 0x61, 0x71, 0x75, 0x69, 0x6e, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x6f, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f,
	0x72, 0x61, 0x2e, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x6f, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x23,
	0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0x7c, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x63, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x2e,
	0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x49, 0x44, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x6f, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x31,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x6d, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x56, 0x65, 0x74, 0x6f, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x6f, 0x52,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x65, 0x74, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x6f, 0x72, 0x61, 0x2e, 0x56, 0x65, 0x74, 0x6f, 0x52, 0x05, 0x76, 0x65, 0x74, 0x6f, 0x73,
	0x22, 0x4b, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x6e,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x6f,
	0x52, 0x0b, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x22, 0x9d, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e,
	0x49, 0x44, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x6f, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65,
	0x6e, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x65, 0x74, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72,
	0x61, 0x2e, 0x56, 0x65, 0x74, 0x6f, 0x52, 0x05, 0x76, 0x65, 0x74, 0x6f, 0x73, 0x22, 0x3a, 0x0a,
	0x08, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x6e, 0x63, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x6f, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x22, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x6e,
	0x67, 0x53, 0x69, 0x6e, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x98, 0x03, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x6f, 0x72, 0x61, 0x12, 0x4b, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x72, 0x12, 0x1e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61,
	0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x1a, 0x1e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x12, 0x5c, 0x0a, 0x14, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x24, 0x2e, 0x65, 0x78, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x69, 0x6f,
	0x1a, 0x1e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f,
	0x12, 0x52, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x65,
	0x74, 0x6f, 0x73, 0x12, 0x1f, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72,
	0x61, 0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x56,
	0x65, 0x74, 0x6f, 0x73, 0x1a, 0x1e, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f,
	0x72, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x6f, 0x12, 0x4d, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61,
	0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1c, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x1c, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64,
	0x6f, 0x72, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x3b, 0x0a, 0x0b, 0x53, 0x69, 0x6e, 0x63, 0x72, 0x6f, 0x6e, 0x69, 0x7a,
	0x61, 0x72, 0x12, 0x15, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x6e, 0x63, 0x1a, 0x15, 0x2e, 0x65, 0x78, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x53, 0x69, 0x6e, 0x63,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x6f, 0x72,
	0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_expendedora_proto_rawDescOnce sync.Once
	file_expendedora_proto_rawDescData = file_expendedora_proto_rawDesc
)

func file_expendedora_proto_rawDescGZIP() []byte {
	file_expendedora_proto_rawDescOnce.Do(func() {
		file_expendedora_proto_rawDescData = protoimpl.X.CompressGZIP(file_expendedora_proto_rawDescData)
	})
	return file_expendedora_proto_rawDescData
}

var file_expendedora_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_expendedora_proto_goTypes = []interface{}{
	(*ItemInventario)(nil),          // 0: expendedora.ItemInventario
	(*Veto)(nil),                    // 1: expendedora.Veto
	(*IDProceso)(nil),               // 2: expendedora.IDProceso
	(*SolicitudRegistro)(nil),       // 3: expendedora.SolicitudRegistro
	(*RespuestaRegistro)(nil),       // 4: expendedora.RespuestaRegistro
	(*ActualizacionInventario)(nil), // 5: expendedora.ActualizacionInventario
	(*ActualizacionVetos)(nil),      // 6: expendedora.ActualizacionVetos
	(*SolicitudEstado)(nil),         // 7: expendedora.SolicitudEstado
	(*RespuestaEstado)(nil),         // 8: expendedora.RespuestaEstado
	(*PingSinc)(nil),                // 9: expendedora.PingSinc
	(*PongSinc)(nil),                // 10: expendedora.PongSinc
}
var file_expendedora_proto_depIdxs = []int32{
	2,  // 0: expendedora.SolicitudRegistro.id:type_name -> expendedora.IDProceso
	2,  // 1: expendedora.ActualizacionInventario.origen:type_name -> expendedora.IDProceso
	0,  // 2: expendedora.ActualizacionInventario.items:type_name -> expendedora.ItemInventario
	2,  // 3: expendedora.ActualizacionVetos.origen:type_name -> expendedora.IDProceso
	1,  // 4: expendedora.ActualizacionVetos.vetos:type_name -> expendedora.Veto
	2,  // 5: expendedora.SolicitudEstado.solicitante:type_name -> expendedora.IDProceso
	2,  // 6: expendedora.RespuestaEstado.origen:type_name -> expendedora.IDProceso
	0,  // 7: expendedora.RespuestaEstado.items:type_name -> expendedora.ItemInventario
	1,  // 8: expendedora.RespuestaEstado.vetos:type_name -> expendedora.Veto
	2,  // 9: expendedora.PingSinc.origen:type_name -> expendedora.IDProceso
	3,  // 10: expendedora.Expendedora.Registrar:input_type -> expendedora.SolicitudRegistro
	5,  // 11: expendedora.Expendedora.ActualizarInventario:input_type -> expendedora.ActualizacionInventario
	6,  // 12: expendedora.Expendedora.ActualizarVetos:input_type -> expendedora.ActualizacionVetos
	7,  // 13: expendedora.Expendedora.SolicitarEstado:input_type -> expendedora.SolicitudEstado
	9,  // 14: expendedora.Expendedora.Sincronizar:input_type -> expendedora.PingSinc
	4,  // 15: expendedora.Expendedora.Registrar:output_type -> expendedora.RespuestaRegistro
	4,  // 16: expendedora.Expendedora.ActualizarInventario:output_type -> expendedora.RespuestaRegistro
	4,  // 17: expendedora.Expendedora.ActualizarVetos:output_type -> expendedora.RespuestaRegistro
	8,  // 18: expendedora.Expendedora.SolicitarEstado:output_type -> expendedora.RespuestaEstado
	10, // 19: expendedora.Expendedora.Sincronizar:output_type -> expendedora.PongSinc
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_expendedora_proto_init() }
func file_expendedora_proto_init() {
	if File_expendedora_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expendedora_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInventario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Veto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDProceso); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudRegistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaRegistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualizacionInventario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualizacionVetos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingSinc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expendedora_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongSinc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expendedora_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expendedora_proto_goTypes,
		DependencyIndexes: file_expendedora_proto_depIdxs,
		MessageInfos:      file_expendedora_proto_msgTypes,
	}.Build()
	File_expendedora_proto = out.File
	file_expendedora_proto_rawDesc = nil
	file_expendedora_proto_goTypes = nil
	file_expendedora_proto_depIdxs = nil
}
